'use client';

import { useState } from 'react';
import { Search, CheckCircle2, Clock, AlertCircle, Calendar, GraduationCap, User, FileText, ArrowRight } from 'lucide-react';
import { lookupApplicationStatus } from '../actions';

const STAGES = [
  { key: 'Application', label: 'Application Submitted', desc: 'Initial details received and queued for review.' },
  { key: 'Verification', label: 'Document Audit', desc: 'School administrators verify submitted certificates & records.' },
  { key: 'Interview', label: 'Student Interview', desc: 'Virtual or face-to-face evaluation meeting.' },
  { key: 'Assessment', label: 'Entrance Assessment', desc: 'Skill test or placement exam.' },
  { key: 'Acceptance', label: 'Offer of Admission', desc: 'Official offer letter generated by the school.' },
  { key: 'Enrollment', label: 'Fee & Tuition Payment', desc: 'Financial clearance and admission fee settlement.' },
  { key: 'Allocation', label: 'Official Class Allocation', desc: 'Assigned to class section & added to active roster.' },
];

export function StatusClient({ tenantSlug, schoolName }: { tenantSlug: string; schoolName: string }) {
  const [query, setQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<any>(null);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setIsSearching(true);
    setError(null);
    setResult(null);

    const res = await lookupApplicationStatus(tenantSlug, query.trim());
    setIsSearching(false);

    if (res.success && res.applicant) {
      setResult(res);
    } else {
      setError(res.error || 'No matching application found.');
    }
  };

  const currentStageIndex = result
    ? STAGES.findIndex((s) => s.key === result.applicant.stage)
    : -1;

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Search Header Card */}
      <div className="glass-card p-6 sm:p-8 space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-[hsl(var(--text-primary))]">Track Your Admission Status</h2>
          <p className="text-sm text-[hsl(var(--text-secondary))] mt-1">
            Enter your Application Reference Code (e.g., <code className="font-mono font-bold text-[hsl(var(--accent))]">APP-849201AB</code>) or applicant details below.
          </p>
        </div>

        <form onSubmit={handleSearch} className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Search className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-[hsl(var(--text-tertiary))]" />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="e.g. APP-849201AB"
              className="w-full pl-12 pr-4 py-3 bg-[hsl(var(--bg-tertiary))] border border-[hsl(var(--border))] rounded-xl text-[hsl(var(--text-primary))] text-sm focus:outline-none focus:border-[hsl(var(--accent))] uppercase font-mono font-bold tracking-wider"
            />
          </div>
          <button
            type="submit"
            disabled={isSearching || !query.trim()}
            className="px-6 py-3 bg-gradient-to-r from-[hsl(var(--accent))] to-[hsl(var(--accent-hover))] text-white font-bold text-sm rounded-xl hover:opacity-90 transition-opacity disabled:opacity-50 flex items-center justify-center gap-2"
          >
            {isSearching ? 'Searching...' : 'Lookup Status'}
          </button>
        </form>

        {error && (
          <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-500 text-sm flex items-center gap-3">
            <AlertCircle className="w-5 h-5 shrink-0" />
            <span>{error}</span>
          </div>
        )}
      </div>

      {/* Result Display */}
      {result && (
        <div className="space-y-8 animate-fade-in">
          {/* Summary Banner */}
          <div className="glass-card p-6 sm:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-2">
              <span className="text-xs uppercase tracking-wider font-mono font-extrabold text-[hsl(var(--accent))] bg-[hsl(var(--accent)/0.1)] px-3 py-1 rounded-full border border-[hsl(var(--accent)/0.2)]">
                {result.applicant.referenceCode}
              </span>
              <h3 className="text-2xl font-bold text-[hsl(var(--text-primary))]">{result.applicant.name}</h3>
              <div className="flex flex-wrap gap-4 text-xs text-[hsl(var(--text-secondary))] pt-1">
                <span className="flex items-center gap-1.5">
                  <GraduationCap className="w-4 h-4 text-[hsl(var(--text-tertiary))]" /> Grade: <strong>{result.applicant.targetGrade}</strong>
                </span>
                <span className="flex items-center gap-1.5">
                  <User className="w-4 h-4 text-[hsl(var(--text-tertiary))]" /> Parent: <strong>{result.applicant.parentName}</strong>
                </span>
                <span className="flex items-center gap-1.5">
                  <Calendar className="w-4 h-4 text-[hsl(var(--text-tertiary))]" /> Submitted: <strong>{new Date(result.applicant.appliedDate).toLocaleDateString()}</strong>
                </span>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-[hsl(var(--bg-tertiary))] border border-[hsl(var(--border))] text-center min-w-[200px]">
              <span className="text-xs text-[hsl(var(--text-tertiary))] uppercase font-semibold">Current Stage</span>
              <p className="text-lg font-extrabold text-[hsl(var(--accent))] mt-1">
                {result.applicant.stage}
              </p>
            </div>
          </div>

          {/* 7-Stage Live Pipeline Tracker */}
          <div className="glass-card p-6 sm:p-8 space-y-6">
            <h4 className="text-lg font-bold text-[hsl(var(--text-primary))] flex items-center gap-2">
              <FileText className="w-5 h-5 text-[hsl(var(--accent))]" /> Admissions Pipeline Progress
            </h4>

            <div className="space-y-6 relative before:absolute before:left-4 before:top-3 before:bottom-3 before:w-0.5 before:bg-[hsl(var(--border))] pl-2">
              {STAGES.map((stage, idx) => {
                const isCompleted = idx < currentStageIndex;
                const isCurrent = idx === currentStageIndex;
                const isPending = idx > currentStageIndex;

                return (
                  <div key={stage.key} className="relative flex items-start gap-4 pl-6 group">
                    {/* Status Dot / Icon */}
                    <div
                      className={`absolute left-0 top-1 w-8 h-8 rounded-full flex items-center justify-center -translate-x-1/2 transition-colors ${
                        isCompleted
                          ? 'bg-emerald-500 text-white shadow-md shadow-emerald-500/20'
                          : isCurrent
                          ? 'bg-[hsl(var(--accent))] text-white shadow-lg shadow-[hsl(var(--accent)/0.3)] ring-4 ring-[hsl(var(--accent)/0.15)] animate-pulse'
                          : 'bg-[hsl(var(--bg-tertiary))] text-[hsl(var(--text-tertiary))] border border-[hsl(var(--border))]'
                      }`}
                    >
                      {isCompleted ? (
                        <CheckCircle2 className="w-5 h-5" />
                      ) : isCurrent ? (
                        <Clock className="w-5 h-5" />
                      ) : (
                        <span className="text-xs font-bold">{idx + 1}</span>
                      )}
                    </div>

                    <div className="flex-1 space-y-1">
                      <div className="flex items-center gap-3">
                        <h5
                          className={`font-bold text-sm ${
                            isCurrent
                              ? 'text-[hsl(var(--accent))] font-extrabold text-base'
                              : isCompleted
                              ? 'text-[hsl(var(--text-primary))]'
                              : 'text-[hsl(var(--text-tertiary))]'
                          }`}
                        >
                          {stage.label}
                        </h5>
                        {isCurrent && (
                          <span className="px-2.5 py-0.5 rounded-full text-[10px] uppercase tracking-wider font-extrabold bg-[hsl(var(--accent)/0.1)] text-[hsl(var(--accent))] border border-[hsl(var(--accent)/0.2)]">
                            In Progress
                          </span>
                        )}
                        {isCompleted && (
                          <span className="px-2.5 py-0.5 rounded-full text-[10px] uppercase tracking-wider font-extrabold bg-emerald-500/10 text-emerald-500 border border-emerald-500/20">
                            Completed
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-[hsl(var(--text-secondary))]">{stage.desc}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
