'use server';

import { createAdminClient } from '@/lib/supabase/admin';

export async function createTenantAdmin(email: string, name: string, tempPassword?: string, tenantId?: string) {
  if (!email) throw new Error('Email is required');
  
  const supabaseAdmin = createAdminClient();
  const password = tempPassword || Math.random().toString(36).slice(-10) + 'A1!';

  // 1. Create the user in Auth
  const { data: user, error: authErr } = await supabaseAdmin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: {
      full_name: name,
    }
  });

  if (authErr) {
    if (authErr.message.includes('already registered')) {
      throw new Error('A user with this email already exists.');
    }
    throw new Error(`Failed to create admin user: ${authErr.message}`);
  }

  // 2. Link them to the tenant if tenantId is provided
  if (user.user && tenantId) {
    // We update the profile that was auto-generated by the trigger
    const { error: profileErr } = await supabaseAdmin.from('profiles').update({
      tenant_id: tenantId,
      role: 'school_admin',
      full_name: name || 'Admin',
    }).eq('id', user.user.id);
    
    if (profileErr) {
      console.error('Failed to link admin to tenant:', profileErr);
    }
  }

  return { success: true, userId: user.user?.id };
}
